version: "3"

services:
  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
      image: rheinwein/examplevotingapp-vote
    command: python app.py
    volumes:
     - ./vote:/app
    #depends_on:
    #  - db
    cached: true

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
      image: rheinwein/examplevotingapp-result
    command: nodemon server.js
    volumes:
      - ./result:/app
    #depends_on:
    #  - db
    cached: true

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
      image: rheinwein/examplevotingapp-worker
    #depends_on:
    #  - redis
    cached: true

  redis:
    image: redis:alpine
    container_name: redis

  db:
    #image: healthcheck/postgres:alpine
    image: postgres:9.6
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"

  google-cloud-deployment:
    image: codeship/google-cloud-deployment
    encrypted_env_file: gke.encrypted
    entrypoint: "/bin/bash"
    volumes:
      - ./deploy:/deploy
